# -*- coding: utf-8 -*-
"""OurGreatHackathonScript.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nx1Gl-owi9CShBP4kecSmcvaXYTdOBkp

# Example script for Hackathon

Within each cycle of active learning, you can:

1. Collect training data (original training data + your query data).

2. Train a prediction model to predict the DMS_score for each mutant (e.g., M0A).

3. Use the trained model to predict the score for all mutant in the test set.

4. Select query mutants for next round based on certain criteria. You may want to make sure you don't query the same mutant twice as you only have a limited chances of making queries in total.
"""

import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from torch.utils.data import DataLoader, Dataset
import random
from copy import deepcopy
import pandas as pd
from scipy.stats import spearmanr
import argparse
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

"""## 1. collect training data

Upload `sequence.fasta`, `train.csv`, and `test.csv` to the current runtime:

1. click the folder icon on the left

2. click the upload icon and upload the files to the current directory
"""

with open('sequence.fasta', 'r') as f:
  data = f.readlines()

sequence_wt = data[1].strip()
sequence_wt

len(sequence_wt)

def get_mutated_sequence(mut, sequence_wt):
  wt, pos, mt = mut[0], int(mut[1:-1]), mut[-1]
  #wt is first char
  #pos is second char to second to last char
  #mt is last char

  #Each row in the dataset contains:
  #First character: Wild-type amino acid (e.g., M)
  #Number: 0-based position in the sequence (e.g., 0, 5, 10)
  #Last character: Mutated amino acid (e.g., A, C, T, V)

  sequence = deepcopy(sequence_wt)
  #sequence is wildtype (most common natural type) of the target protein

  #returns the mutated version of the wildtype
  return sequence[:pos]+mt+sequence[pos+1:]

df_train = pd.read_csv('train.csv')
df_train['sequence'] = df_train.mutant.apply(lambda x: get_mutated_sequence(x, sequence_wt))
df_train

df_test = pd.read_csv('test.csv')
df_test['sequence'] = df_test.mutant.apply(lambda x: get_mutated_sequence(x, sequence_wt))
df_test

# TODO: integrate the query data that you acquired each round into df_train

"""## 2. Train a prediction model

Here, we provided a linear regression model and used one-hot encoding to encode each variant. You would need to build your own model to achieve better performances.

Hint: you can perform cross-validation on the training set to evaluate your predictor before making predictions on the test set.
"""

'''hyperparameters'''

seq_length = 656
seed = 0 # seed for splitting the validation set
val_ratio = 0.2 # proportion of validation set

class ProteinDataset(Dataset):
    def __init__(self, df, istrain=True):

        alphabet = 'ACDEFGHIKLMNPQRSTVWY'
        map_a2i = {j:i for i,j in enumerate(alphabet)}
        map_i2a = {i:j for i,j in enumerate(alphabet)}

        self.df = df

        self.num_samples = len(self.df)
        self.seq_length = len(self.df.sequence.values[0])
        self.num_channels = 20

        # TODO: replace one-hot encodings with your own encodings
        self.encodings = np.zeros((self.num_samples, 21)).astype(np.float32)
        self.targets = np.zeros(self.num_samples).astype(np.float32)

        if istrain:
            for it, (mutation, target) in enumerate(self.df[['mutant', 'DMS_score']].values):
                index = int(mutation[1:-1])
                newVal = mutation[-1]
                self.encodings[it, 0] = index / seq_length
                self.encodings[it, map_a2i[newVal] + 1] = 1
                self.targets[it] = target
        else:
            for it, mutation in enumerate(self.df['mutant'].values):
                index = int(mutation[1:-1])
                newVal = mutation[-1]
                self.encodings[it, 0] = index / seq_length
                self.encodings[it, map_a2i[newVal] + 1] = 1


    def __len__(self):
        return self.num_samples

    def __getitem__(self, idx):
        return torch.tensor(self.encodings[idx]), torch.tensor(self.targets[idx])

train_dataset = ProteinDataset(df_train)
test_dataset = ProteinDataset(df_test, istrain=False)

# split validation set
train_dataset, val_dataset = train_test_split(train_dataset, test_size=val_ratio, random_state=seed, shuffle=True)

# TODO: revise according to your own model
train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=64, shuffle=False)
test_loader = DataLoader(test_dataset, batch_size=64, shuffle=False)

#My own class for predictive model

class ProteinNet(nn.Module):
    def __init__(self, inputDim):
        super(ProteinNet, self).__init__()
        self.layers = nn.Sequential(
            nn.Linear(inputDim, 128),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Dropout(.2),
            nn.Linear(64, 1),
            nn.Sigmoid()
        )

    def forward(self, x):
        return self.layers(x)

#Train time
def train(model, train_loader, val_loader):
  epochs = 1000
  lr = .001
  criterion = nn.MSELoss()
  optimizer = optim.Adam(model.parameters(), lr)

  for epoch in range(epochs):
      model.train()
      lossTotal = 0
      for X, y in train_loader:
          X = X.to(device)
          y = y.to(device)
          optimizer.zero_grad()
          predictions = model(X.float())
          loss = criterion(predictions, y.float().view(-1, 1))
          loss.backward()
          optimizer.step()
          lossTotal += loss.item()
      with torch.no_grad():
          model.eval()
          lossValTotal = 0
          valPreds = []
          valTargets = []
          for X, y in val_loader:
              X = X.to(device)
              y = y.to(device)
              predictions = model(X.float())
              loss = criterion(predictions, y.float().view(-1, 1))
              lossValTotal += loss.item()

              valPreds.extend(predictions.cpu().numpy().flatten())
              valTargets.extend(y.cpu().numpy().flatten())
          spearmanVal = spearmanr(valTargets, valPreds)[0]
      print(f"Epoch {epoch+1}/{epochs}, Loss: {lossTotal/len(train_loader)}, Val Loss: {lossValTotal/len(val_loader)}, SpearMan: {spearmanVal:.4f}")

# TODO: build your own prediction model to replace linear regression
# Hint: don't forget to use the validation set: you can either integrate the validation data into the training set or use it separately for early stopping

X_train, y_train = next(iter(train_loader))

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

inputDim = X_train.shape[1]
model1 = ProteinNet(inputDim).to(device)
model2 = ProteinNet(inputDim).to(device)
model3 = ProteinNet(inputDim).to(device)
model4 = ProteinNet(inputDim).to(device)
model5 = ProteinNet(inputDim).to(device)

train(model1, train_loader, val_loader)
train(model2, train_loader, val_loader)
train(model3, train_loader, val_loader)
train(model4, train_loader, val_loader)
train(model5, train_loader, val_loader)

def predict(model, test_loader):
  model.eval()
  totalPredictions = []

  with torch.no_grad():
      for X, y in test_loader:
          X = X.to(device)
          predictions = model(X.flatten(start_dim=1))
          totalPredictions.extend(predictions.cpu().numpy().flatten())
  return pd.DataFrame({
          'mutant': df_test['mutant'].values,
          'predicted_score': totalPredictions
      })

#This cell returns a dict that maps mutants to their 5 fitness scores

model_predicts = [predict(m, test_loader) for m in [model1, model2, model3, model4, model5]]
combined = pd.concat(model_predicts)
mutant_dict = combined.groupby('mutant')['predicted_score'].apply(list).to_dict()
df_test['DMS_score_predicted'] = df_test['mutant'].apply(lambda x: np.mean(mutant_dict[x]))
print(len(mutant_dict))
print(mutant_dict)

#Find the top 10 based on avg fitness score:

averages = []
for mutation in mutant_dict:
  averages.append((mutation, np.mean(mutant_dict[mutation])))

averages.sort(key=lambda x: x[1], reverse=True)
print(averages[:10])

bestTenList = []
for i in range(10):
  bestTenList.append(averages[i][0])

print(bestTenList)
with open('top10.txt', 'w') as f:
  for mutant in bestTenList:
    f.write(mutant+'\n')

df_pred_model1 = predict(model1, test_loader)
df_test['DMS_score_predicted'] = df_pred_model1['predicted_score']

# Find top 10 based on model1 predictions
df_pred_model1 = predict(model1, test_loader)

scores = list(zip(df_pred_model1['mutant'], df_pred_model1['predicted_score']))

scores.sort(key=lambda x: x[1], reverse=True)

print(scores[:10])

bestTenList = [mutation for mutation, _ in scores[:10]]

print(bestTenList)

with open('top10.txt', 'w') as f:
    for mutant in bestTenList:
        f.write(mutant + '\n')

#This cell returns a dict that maps mutants to their 5 rankings (based on fitness score)

model_predicts = []
models = [model1, model2, model3, model4, model5]

for i, m in enumerate(models):
    df_pred = predict(m, test_loader)
    df_pred = df_pred.copy()
    df_pred["model_id"] = i
    model_predicts.append(df_pred)

combined = pd.concat(model_predicts, ignore_index=True)

combined["rank"] = combined.groupby("model_id")["predicted_score"].rank(method="average", ascending=False)

rankingDict = (combined.sort_values(["mutant", "model_id"]).groupby("mutant")["rank"].apply(list).to_dict())

print(len(rankingDict))
print(rankingDict)

df_test[['mutant', 'DMS_score_predicted']].to_csv('predictions.csv')

from google.colab import drive
drive.mount('/content/drive')

"""## 3. Select query for next round"""

df_test.sort_values('DMS_score_predicted', ascending=False).head(100)

trainSet = set(df_train['mutant'])
print(len(trainSet))
print(trainSet)

#SAMPLE BY VARIANCE (QUERY 1)

thompsonArr = []
thompsonQueries = []

for mutation in rankingDict:
  currMutationArr = rankingDict[mutation]
  var = np.var(currMutationArr, ddof=1)
  thompsonArr.append((mutation, var))

thompsonArr.sort(key=lambda x: x[1], reverse=True)
print(thompsonArr)

currIndex = 0
while len(thompsonQueries) < 100:
  if thompsonArr[currIndex][0] not in trainSet:
    thompsonQueries.append(thompsonArr[currIndex][0])
  currIndex += 1

print(len(thompsonQueries))
print(thompsonQueries)

#SANITY CHECK (Make sure there are none from current test set)

for mutant in thompsonQueries:
  if mutant in trainSet:
    print(mutant)

with open('query.txt', 'w') as f:
  for mutant in thompsonQueries:
    f.write(mutant+'\n')

#SAMPLE BY UCB (QUERY 2)

ucbArr = []
ucbQueries = []

for mutation in rankingDict:
  currMutationArr = rankingDict[mutation]
  std = np.std(currMutationArr, ddof=1)
  mean = np.mean(currMutationArr)
  ucbScore = mean - (4 * std)
  ucbArr.append((mutation, ucbScore))

ucbArr.sort(key=lambda x: x[1])
print(ucbArr)

currIndex = 0
while len(ucbQueries) < 100:
  if ucbArr[currIndex][0] not in trainSet:
    ucbQueries.append(ucbArr[currIndex][0])
  currIndex += 1

print(len(ucbArr))
print(ucbQueries)

#SANITY CHECK (Make sure there are none from current test set)

for mutant in ucbQueries:
  if mutant in trainSet:
    print(mutant)

with open('query.txt', 'w') as f:
  for mutant in ucbQueries:
    f.write(mutant+'\n')

#GREEDY SAMPLING (QUERY 3)

greedyArr = []
greedyQueries = []

for mutation in rankingDict:
  currMutationArr = rankingDict[mutation]
  mean = np.mean(currMutationArr)
  greedyArr.append((mutation, mean))

greedyArr.sort(key=lambda x: x[1])
print(greedyArr)

currIndex = 0
while len(greedyQueries) < 100:
  if greedyArr[currIndex][0] not in trainSet:
    greedyQueries.append(greedyArr[currIndex][0])
  currIndex += 1
print(len(greedyQueries))
print(greedyQueries)

#SANITY CHECK (Make sure there are none from current test set)

for mutant in greedyQueries:
  if mutant in trainSet:
    print(mutant)

with open('query.txt', 'w') as f:
  for mutant in greedyQueries:
    f.write(mutant+'\n')